// <auto-generated />
using System;
using BudgetAnalyzer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetAnalyzer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710173253_AddCategoriesTable")]
    partial class AddCategoriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetAnalyzer.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#4287f5",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#f5a442",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#42c88a",
                            Name = "Eating Out"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#2e9e4f",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#9b59b6",
                            Name = "Wallet Transfer"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#34495e",
                            Name = "Investment"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#e67e22",
                            Name = "Gift Card"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#f1c40f",
                            Name = "Crypto"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#1abc9c",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#e91e63",
                            Name = "Grooming"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#7f8c8d",
                            Name = "Credit Card"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#e74c3c",
                            Name = "Person-to-Person"
                        },
                        new
                        {
                            Id = 13,
                            Color = "#27ae60",
                            Name = "Income"
                        },
                        new
                        {
                            Id = 14,
                            Color = "#bdc3c7",
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("BudgetAnalyzer.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceBank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatementMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
